export const types = {
    LOGIN: '[AUTH] LOGIN',
    LOGOUT: '[AUTH] LOGOUT',

    LISTAR_USUARIOS: '[CHAT] LISTAR_USUARIOS',
    CHAT_ACTIVO: '[CHAT] CHAT_ACTIVO',
    NUEVO_MENSAJE: '[CHAT] NUEVO_MENSAJE',
    CARGAR_MENSAJES: '[CHAT] CARGAR_MENSAJES',
}