export const types = {
    LOGIN: '[AUTH] LOGIN',
    LOGOUT: '[AUTH] LOGOUT',


    LISTAR_USUARIOS: 'LISTAR_USUARIOS',
    CHAT_ACTIVO: 'CHAT_ACTIVO',
    NUEVO_MENSAJE: 'NUEVO_MENSAJE',
    CARGAR_MENSAJES: 'CARGAR_MENSAJES',
}